DROP SCHEMA IF EXISTS aula171_exemplo01;

CREATE SCHEMA aula171_exemplo01;


CREATE TABLE aula171_exemplo01.BANCOS (
	ID			INT PRIMARY KEY AUTO_INCREMENT,
    NUMERO		VARCHAR(10) NOT NULL UNIQUE,
    NOME 		VARCHAR(100) NOT NULL
);

CREATE TABLE aula171_exemplo01.AGENCIAS (
	ID			INT PRIMARY KEY AUTO_INCREMENT,
    NUMERO		VARCHAR(20) NOT NULL UNIQUE,
    NOME		VARCHAR(100) NOT NULL,
    BANCO_ID	INT,
    FOREIGN KEY(BANCO_ID) 
    REFERENCES aula171_exemplo01.BANCOS(ID)
);


INSERT INTO aula171_exemplo01.bancos 
(numero, nome)
VALUES
('399', 'HSBC'),
('001', 'BANCO DO BRASIL'),
('217', 'BRADESCO');

INSERT INTO aula171_exemplo01.bancos 
(numero, nome)
VALUES
('260', 'NU PAGAMENTOS S.A (NUBANK)'),
('290',	'PAGSEGURO INTERNET S.A (PAGBANK)'),
('380',	'PICPAY SERVIÇOS S.A.');